# Generated by Django 5.2.8 on 2026-01-17 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the bed type (max 256 characters)', max_length=256, null=True, unique=True)),
                ('code', models.CharField(blank=True, help_text='A short code to identify the bed type (max 50 characters)', max_length=250, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the bed type')),
                ('is_active', models.BooleanField(default=True, help_text='Is the bed type active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the bed type was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the bed type was last updated')),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the block (max 256 characters)', max_length=256, null=True, unique=True)),
                ('code', models.CharField(blank=True, help_text='A short code to identify the block (max 50 characters)', max_length=250, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the block')),
                ('is_active', models.BooleanField(default=True, help_text='Is the block active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the block was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the room status was last updated')),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the floor (max 256 characters)', max_length=256, null=True, unique=True)),
                ('code', models.CharField(blank=True, help_text='A short code to identify the floor (max 50 characters)', max_length=250, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the floor')),
                ('is_active', models.BooleanField(default=True, help_text='Is the floor active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the floor was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the floor was last updated')),
            ],
        ),
        migrations.CreateModel(
            name='RoomAmnity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the room category (max 100 characters)', max_length=100, null=True, unique=True)),
                ('code', models.CharField(blank=True, help_text='A short code to identify the room category (max 50 characters)', max_length=50, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the room category')),
                ('is_active', models.BooleanField(default=True, help_text='Is the room category active?')),
                ('chargeable', models.BooleanField(default=True, help_text='Is the room category chargeable?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the room category was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the room category was last updated')),
            ],
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the room category (max 100 characters)', max_length=100, null=True, unique=True)),
                ('code', models.CharField(blank=True, help_text='A short code to identify the room category (max 50 characters)', max_length=50, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the room category')),
                ('is_active', models.BooleanField(default=True, help_text='Is the room category active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the room category was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the room category was last updated')),
            ],
        ),
        migrations.CreateModel(
            name='RoomStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the room status (max 256 characters)', max_length=256, null=True, unique=True)),
                ('code', models.CharField(blank=True, help_text='A short code to identify the room status (max 50 characters)', max_length=250, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the room status')),
                ('is_active', models.BooleanField(default=True, help_text='Is the room status active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the room status was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the room status was last updated')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, help_text='A short code to identify the room type (max 50 characters)', max_length=50, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('max_adults', models.PositiveIntegerField(default=2)),
                ('max_children', models.PositiveIntegerField(default=0)),
                ('default_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomViewType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the room category (max 256 characters)', max_length=256, null=True, unique=True)),
                ('code', models.CharField(blank=True, help_text='A short code to identify the room category (max 50 characters)', max_length=50, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the room category')),
                ('is_active', models.BooleanField(default=True, help_text='Is the room category active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the room category was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the room category was last updated')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(blank=True, help_text='Room number (max 256 characters)', max_length=256, null=True)),
                ('current_status', models.CharField(blank=True, help_text='Current status of the room (max 256 characters)', max_length=256, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Remarks of the room (max 256 characters)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the room active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the room was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the room was last updated')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.floor')),
                ('amenities', models.ManyToManyField(related_name='rooms', to='rooms.roomamnity')),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.roomcategory')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.roomtype')),
                ('view_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.roomviewtype')),
            ],
        ),
    ]
