# Generated by Django 5.2.8 on 2026-01-24 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_setup', '0003_country_created_at_country_updated_at_and_more'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Enter Name', max_length=255, null=True, verbose_name='Name')),
                ('code', models.CharField(blank=True, help_text='Enter Code', max_length=255, null=True, verbose_name='Code')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Enter Rate', max_digits=10, verbose_name='Rate')),
                ('capacity', models.IntegerField(help_text='Enter Capacity', verbose_name='Capacity')),
                ('extra_bed_charge', models.DecimalField(decimal_places=2, help_text='Enter Extra Bed Charge', max_digits=10, verbose_name='Extra Bed Charge')),
                ('is_active', models.BooleanField(default=True, help_text='Is Active', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_type', models.ForeignKey(help_text='Select Tax Type', on_delete=django.db.models.deletion.CASCADE, to='master_setup.taxtype', verbose_name='Tax Type')),
            ],
            options={
                'verbose_name': 'Room Rate',
                'verbose_name_plural': 'Room Rates',
                'ordering': ['name'],
            },
        ),
    ]
