# Generated by Django 5.2.8 on 2026-01-24 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_roomallotment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomallotment',
            old_name='alloated_at',
            new_name='alloted_at',
        ),
        migrations.RenameField(
            model_name='roomallotment',
            old_name='alloated_by',
            new_name='alloted_by',
        ),
    ]
