# Generated by Django 5.2.8 on 2026-01-17 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the account type (max 256 characters)', max_length=256, null=True, unique=True)),
                ('code', models.CharField(blank=True, help_text='Code of the account type (max 256 characters)', max_length=256, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the account type', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the account type active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the account type was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the account type was last updated')),
            ],
        ),
        migrations.CreateModel(
            name='BookingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the booking source (max 256 characters)', max_length=256, null=True, unique=True)),
                ('code', models.CharField(blank=True, help_text='Code of the booking source (max 256 characters)', max_length=256, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the booking source', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the booking source active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the booking source was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the booking source was last updated')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the payment mode (max 256 characters)', max_length=256, null=True, unique=True)),
                ('code', models.CharField(blank=True, help_text='Code of the payment mode (max 256 characters)', max_length=256, null=True, unique=True)),
                ('symbol', models.CharField(blank=True, help_text='Symbol of the payment mode (max 256 characters)', max_length=256, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the payment mode active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the payment mode was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the payment mode was last updated')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the department (max 256 characters)', max_length=256, null=True, unique=True)),
                ('code', models.CharField(blank=True, help_text='Code of the department (max 256 characters)', max_length=256, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the department', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the department active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the department was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the department was last updated')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the discount type (max 256 characters)', max_length=256, null=True, unique=True)),
                ('code', models.CharField(blank=True, help_text='Code of the discount type (max 256 characters)', max_length=256, null=True, unique=True)),
                ('discount_type', models.CharField(blank=True, help_text='Type of the discount type (max 256 characters)', max_length=256, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the discount type', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the discount type active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the discount type was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the discount type was last updated')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the employee type (max 256 characters)', max_length=256, null=True, unique=True)),
                ('code', models.CharField(blank=True, help_text='Code of the employee type (max 256 characters)', max_length=256, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the employee type', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the employee type active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the employee type was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the employee type was last updated')),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the event type (max 256 characters)', max_length=256, null=True, unique=True)),
                ('code', models.CharField(blank=True, help_text='Code of the event type (max 256 characters)', max_length=256, null=True, unique=True)),
                ('default_capacity', models.IntegerField(blank=True, help_text='Default capacity of the event type', null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the event type', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the event type active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the event type was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the event type was last updated')),
            ],
        ),
        migrations.CreateModel(
            name='MiscellaneousService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the miscellaneous services (max 256 characters)', max_length=256, null=True, unique=True)),
                ('code', models.CharField(blank=True, help_text='Code of the miscellaneous services (max 256 characters)', max_length=256, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the miscellaneous services', null=True)),
                ('chargeable', models.BooleanField(default=True, help_text='Is the miscellaneous services chargeable?')),
                ('rate', models.DecimalField(blank=True, decimal_places=2, help_text='Rate of the miscellaneous services', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the miscellaneous services active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the miscellaneous services was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the miscellaneous services was last updated')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the notification category (max 256 characters)', max_length=256, null=True, unique=True)),
                ('code', models.CharField(blank=True, help_text='Code of the notification category (max 256 characters)', max_length=256, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the notification category', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the notification category active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the notification category was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the notification category was last updated')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the parking type (max 256 characters)', max_length=256, null=True, unique=True)),
                ('code', models.CharField(blank=True, help_text='Code of the parking type (max 256 characters)', max_length=256, null=True, unique=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, help_text='Rate of the parking type', max_digits=10, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the parking type', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the parking type active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the parking type was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the parking type was last updated')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the payment mode (max 256 characters)', max_length=256, null=True, unique=True)),
                ('code', models.CharField(blank=True, help_text='Code of the payment mode (max 256 characters)', max_length=256, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the payment mode', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the payment mode active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the payment mode was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the payment mode was last updated')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the salary structure (max 256 characters)', max_length=256, null=True, unique=True)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0.0, help_text='Basic salary', max_digits=10)),
                ('hra', models.DecimalField(decimal_places=2, default=0.0, help_text='HRA', max_digits=10)),
                ('special_allowance', models.DecimalField(decimal_places=2, default=0.0, help_text='Special allowance', max_digits=10)),
                ('medical_allowance', models.DecimalField(decimal_places=2, default=0.0, help_text='Medical allowance', max_digits=10)),
                ('conveyance_allowance', models.DecimalField(decimal_places=2, default=0.0, help_text='Conveyance allowance', max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax', max_digits=10)),
                ('pf', models.DecimalField(decimal_places=2, default=0.0, help_text='PF', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the salary structure was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the salary structure was last updated')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the service category (max 256 characters)', max_length=256, null=True, unique=True)),
                ('code', models.CharField(blank=True, help_text='Code of the service category (max 256 characters)', max_length=256, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the service category', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the service category active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the service category was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the service category was last updated')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the shift type (max 256 characters)', max_length=256, null=True, unique=True)),
                ('code', models.CharField(blank=True, help_text='Code of the shift type (max 256 characters)', max_length=256, null=True, unique=True)),
                ('start_time', models.TimeField(blank=True, help_text='Start time of the shift type', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='End time of the shift type', null=True)),
                ('break_duration', models.DurationField(blank=True, help_text='Break duration of the shift type', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the shift type active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the shift type was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the shift type was last updated')),
            ],
        ),
        migrations.CreateModel(
            name='TaxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the tax type (max 256 characters)', max_length=256, null=True, unique=True)),
                ('code', models.CharField(blank=True, help_text='Code of the tax type (max 256 characters)', max_length=256, null=True, unique=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, help_text='Tax rate (e.g. 10.00 for 10%)', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Description of the tax type', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the tax type active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the tax type was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the tax type was last updated')),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the designation (max 256 characters)', max_length=256, null=True, unique=True)),
                ('code', models.CharField(blank=True, help_text='Code of the designation (max 256 characters)', max_length=256, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the designation active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the designation was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the designation was last updated')),
                ('department', models.ForeignKey(blank=True, help_text='Department of the designation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='master_setup.department')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the notification template (max 256 characters)', max_length=256, null=True, unique=True)),
                ('code', models.CharField(blank=True, help_text='Code of the notification template (max 256 characters)', max_length=256, null=True, unique=True)),
                ('channel', models.CharField(blank=True, help_text='Channel of the notification template (max 256 characters)', max_length=256, null=True, unique=True)),
                ('message_body', models.TextField(blank=True, help_text='Message body of the notification template', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the notification template active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the notification template was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the notification template was last updated')),
                ('notification_category', models.ForeignKey(blank=True, help_text='Notification category of the notification template', null=True, on_delete=django.db.models.deletion.CASCADE, to='master_setup.notificationcategory')),
            ],
        ),
    ]
