# Generated by Django 5.2.8 on 2026-01-17 16:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_setup', '0002_auto_20260117_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='phone_code',
            field=models.CharField(blank=True, help_text="International dialing code (e.g., '1', '44')", max_length=10),
        ),
    ]
