# Generated by Django 5.2.8 on 2026-01-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_setup', '0003_country_created_at_country_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the printer (max 256 characters)', max_length=256, null=True, unique=True)),
                ('code', models.CharField(blank=True, help_text='Code of the printer (max 256 characters)', max_length=256, null=True, unique=True)),
                ('printer_type', models.CharField(blank=True, help_text='Printer type (max 256 characters)', max_length=256, null=True, unique=True)),
                ('ip_address', models.CharField(blank=True, help_text='IP address of the printer (max 256 characters)', max_length=256, null=True, unique=True)),
                ('port', models.IntegerField(blank=True, help_text='Port of the printer (max 256 characters)', null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the printer (max 256 characters)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the printer active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the printer was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the printer was last updated')),
            ],
        ),
    ]
