# Generated by Django 6.0.2 on 2026-02-17 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_setup', '0004_printer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the priority level', max_length=250, null=True)),
                ('code', models.CharField(blank=True, help_text='Code of the priority level', max_length=250, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the priority level', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the priority level active?')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='Create at for the priority level')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='Update at for the priority level')),
                ('create_by', models.ForeignKey(blank=True, help_text='User who created the priority level', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='priority_levels_create_by', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(blank=True, help_text='User who updated the priority level', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='priority_levels_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
