# Generated by Django 6.0.2 on 2026-02-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_setup", "0005_prioritylevel"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bill_type_name", models.CharField(help_text="Name of the bill type", max_length=256, unique=True)),
                ("description", models.TextField(blank=True, help_text="Description of the bill type", null=True)),
                ("is_active", models.BooleanField(default=True, help_text="Is the bill type active?")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date and time when the bill type was created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the bill type was last updated",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bill Type",
                "verbose_name_plural": "Bill Types",
                "ordering": ["bill_type_name"],
            },
        ),
    ]
