# Generated by Django 6.0.2 on 2026-02-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_setup", "0006_billtype"),
    ]

    operations = [
        migrations.CreateModel(
            name="FiscalYear",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fiscal_year_name", models.CharField(help_text="Name of the fiscal year", max_length=256, unique=True)),
                ("start_date", models.DateField(help_text="Start date of fiscal year")),
                ("end_date", models.DateField(help_text="End date of fiscal year")),
                ("description", models.TextField(blank=True, help_text="Description of the fiscal year", null=True)),
                ("is_active", models.BooleanField(default=True, help_text="Is the fiscal year active?")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date and time when the fiscal year was created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the fiscal year was last updated",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiscal Year",
                "verbose_name_plural": "Fiscal Years",
                "ordering": ["-start_date"],
            },
        ),
    ]
