# Generated by Django 5.2.8 on 2026-01-17 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the food type (max 256 characters)', max_length=256, null=True, unique=True)),
                ('code', models.CharField(blank=True, help_text='A short code to identify the food type (max 50 characters)', max_length=250, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the food type')),
                ('is_active', models.BooleanField(default=True, help_text='Is the food type active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the food type was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the food type was last updated')),
            ],
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the menu category (max 256 characters)', max_length=256, null=True, unique=True)),
                ('code', models.CharField(blank=True, help_text='A short code to identify the menu category (max 50 characters)', max_length=250, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the menu category')),
                ('is_active', models.BooleanField(default=True, help_text='Is the menu category active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the menu category was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the menu category was last updated')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the restaurant service type (max 256 characters)', max_length=256, null=True, unique=True)),
                ('code', models.CharField(blank=True, help_text='A short code to identify the restaurant service type (max 50 characters)', max_length=250, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the restaurant service type')),
                ('is_active', models.BooleanField(default=True, help_text='Is the restaurant service type active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the restaurant service type was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the restaurant service type was last updated')),
            ],
        ),
        migrations.CreateModel(
            name='TableSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(blank=True, help_text='Name of the table (max 256 characters)', max_length=256, null=True, unique=True)),
                ('seating_capacity', models.IntegerField(blank=True, help_text='Seating capacity of the table')),
                ('location_area', models.CharField(blank=True, help_text='Location area of the table', max_length=250, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the table active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the table was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the table was last updated')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the menu item (max 256 characters)', max_length=256, null=True, unique=True)),
                ('code', models.CharField(blank=True, help_text='A short code to identify the menu item (max 50 characters)', max_length=250, null=True, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the menu item', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Description of the menu item')),
                ('is_active', models.BooleanField(default=True, help_text='Is the menu item active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the menu item was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the menu item was last updated')),
                ('menu_category', models.ForeignKey(help_text='Menu category to which the menu item belongs', on_delete=django.db.models.deletion.CASCADE, to='restaurant_menu.menucategory')),
            ],
        ),
    ]
