# Generated by Django 5.2.8 on 2026-02-07 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_setup', '0004_printer'),
        ('restaurant_menu', '0002_menusubcategory_delete_foodtype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the menu item (max 256 characters)', max_length=256, null=True, unique=True)),
                ('code', models.CharField(blank=True, help_text='A short code to identify the menu item (max 50 characters)', max_length=250, null=True, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the menu item', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Description of the menu item')),
                ('food_type', models.CharField(blank=True, help_text='Food type of the menu item', max_length=250, null=True)),
                ('recipe_linked', models.BooleanField(default=False, help_text='Is the menu item linked to a recipe?')),
                ('is_active', models.BooleanField(default=True, help_text='Is the menu item active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the menu item was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the menu item was last updated')),
                ('menu_category', models.ForeignKey(help_text='Menu category to which the menu item belongs', on_delete=django.db.models.deletion.CASCADE, to='restaurant_menu.menucategory')),
                ('menu_sub_category', models.ForeignKey(blank=True, help_text='Menu sub category to which the menu item belongs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurant_menu.menusubcategory')),
                ('printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='master_setup.printer')),
                ('tax_type', models.ForeignKey(blank=True, help_text='Tax type to which the menu item belongs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_menu_items', to='master_setup.taxtype')),
            ],
        ),
    ]
