# Generated by Django 5.2.8 on 2026-02-08 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0003_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='food_type',
            field=models.CharField(blank=True, choices=[('Vegetarian', 'Vegetarian'), ('Non-Vegetarian', 'Non-Vegetarian'), ('Vegan', 'Vegan')], help_text='Food type of the menu item', max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the modifier', max_length=255, null=True)),
                ('extra_price', models.DecimalField(blank=True, decimal_places=2, help_text='Extra price of the modifier', max_digits=10, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the modifier', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the modifier active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the modifier was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the modifier was last updated')),
                ('menu_item', models.ForeignKey(blank=True, help_text='Menu item to which the modifier belongs', null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant_menu.menuitem')),
            ],
        ),
    ]
