# Generated by Django 5.2.8 on 2026-02-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0004_alter_menuitem_food_type_modifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the zone (max 256 characters)', max_length=256, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the zone', null=True)),
                ('service_charge_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Service charge percentage', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Is the zone active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the zone was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the zone was last updated')),
            ],
        ),
    ]
