# Generated by Django 5.2.8 on 2026-02-08 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0005_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the table (max 256 characters)', max_length=256, null=True, unique=True)),
                ('seating_capacity', models.IntegerField(blank=True, help_text='Seating capacity of the table')),
                ('location_area', models.CharField(blank=True, help_text='Location area of the table', max_length=250, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the table active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the table was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the table was last updated')),
                ('zone', models.ForeignKey(blank=True, help_text='Zone of the table', null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant_menu.zone')),
            ],
        ),
    ]
