# Generated by Django 5.2.8 on 2026-02-09 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0006_tablesetup'),
        ('rooms', '0004_rename_alloated_at_roomallotment_alloted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, unique=True)),
                ('guest_count', models.IntegerField(default=1)),
                ('guest_name', models.CharField(max_length=100)),
                ('order_start_time', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('kot-sent', 'KOT Sent'), ('partial-served', 'Partial Served'), ('billed', 'Billed'), ('closed', 'Closed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='rooms.room')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='restaurant_menu.tablesetup')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order_item_status', models.CharField(choices=[('ordered', 'Ordered'), ('served', 'Served'), ('cancelled', 'Cancelled')], default='ordered', max_length=20)),
                ('cancel_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='restaurant_menu.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='restaurant_menu.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_menu.modifier')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item_modifiers', to='restaurant_menu.orderitem')),
            ],
            options={
                'unique_together': {('order_item', 'modifier')},
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='modifiers',
            field=models.ManyToManyField(related_name='order_items', through='restaurant_menu.OrderItemModifier', to='restaurant_menu.modifier'),
        ),
    ]
