# Generated by Django 5.2.8 on 2026-02-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0007_order_orderitem_orderitemmodifier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the kitchen (max 256 characters)', max_length=256, null=True, unique=True)),
                ('code', models.CharField(blank=True, help_text='A short code to identify the kitchen (max 250 characters)', max_length=250, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the kitchen', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the kitchen active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the kitchen was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the kitchen was last updated')),
            ],
        ),
    ]
