# Generated by Django 5.2.8 on 2026-02-15 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0008_kitchen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kitchen',
            options={'verbose_name': 'Kitchen', 'verbose_name_plural': 'Kitchens'},
        ),
        migrations.RemoveField(
            model_name='kitchen',
            name='code',
        ),
        migrations.RemoveField(
            model_name='kitchen',
            name='description',
        ),
        migrations.RemoveField(
            model_name='kitchen',
            name='name',
        ),
        migrations.AddField(
            model_name='kitchen',
            name='backup_printer_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Failover printer IP address', null=True, protocol='IPv4'),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='kds_display_id',
            field=models.CharField(blank=True, help_text='Linked KDS display/tablet identifier', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='kitchen_name',
            field=models.CharField(blank=True, help_text='Kitchen name (e.g., Cold Kitchen, Bakery, Bar, Main Galley)', max_length=256, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='kitchen_type',
            field=models.CharField(blank=True, choices=[('food', 'Food'), ('beverage', 'Beverage'), ('shisha', 'Shisha'), ('pastry', 'Pastry')], help_text='Kitchen type', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='printer_ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Network address for thermal printer', null=True, protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this kitchen active?'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='kitchen',
            table='mst_kitchens',
        ),
        migrations.CreateModel(
            name='KOTHeader',
            fields=[
                ('kot_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kot_number', models.CharField(max_length=64, unique=True)),
                ('kot_type', models.CharField(choices=[('new_order', 'New Order'), ('running_order', 'Running Order'), ('void_cancel', 'Void/Cancel KOT')], default='new_order', max_length=20)),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_printed', models.DateTimeField(blank=True, null=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('total_items_count', models.PositiveIntegerField(default=0)),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kot_headers', to='restaurant_menu.kitchen')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kot_headers', to='restaurant_menu.order')),
                ('waiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fired_kots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KOT Header',
                'verbose_name_plural': 'KOT Headers',
                'db_table': 'trn_kot_header',
            },
        ),
        migrations.CreateModel(
            name='KOTAmendment',
            fields=[
                ('amendment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('added', 'Added'), ('cancelled', 'Cancelled'), ('changed', 'Changed')], max_length=20)),
                ('reason_code', models.CharField(choices=[('kitchen_mistake', 'Kitchen mistake'), ('guest_changed_mind', 'Guest changed mind'), ('quality_issue', 'Quality issue')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_kot_amendments', to=settings.AUTH_USER_MODEL)),
                ('original_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kot_amendments', to='restaurant_menu.menuitem')),
                ('kot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='restaurant_menu.kotheader')),
            ],
            options={
                'verbose_name': 'KOT Amendment',
                'verbose_name_plural': 'KOT Amendments',
                'db_table': 'trn_kot_amendments',
            },
        ),
        migrations.CreateModel(
            name='KOTLineItem',
            fields=[
                ('kot_line_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('modifiers_text', models.TextField(blank=True, help_text='Combined add-ons for chef reference')),
                ('cooking_instruction', models.TextField(blank=True, help_text='e.g. "Well Done", "Allergy: Nuts"')),
                ('item_status', models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('bounced', 'Bounced'), ('served', 'Served')], default='pending', max_length=20)),
                ('timestamp_start_cooking', models.DateTimeField(blank=True, null=True)),
                ('timestamp_ready', models.DateTimeField(blank=True, null=True)),
                ('chef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_kot_line_items', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kot_line_items', to='restaurant_menu.menuitem')),
                ('kot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='restaurant_menu.kotheader')),
            ],
            options={
                'verbose_name': 'KOT Line Item',
                'verbose_name_plural': 'KOT Line Items',
                'db_table': 'trn_kot_line_items',
            },
        ),
        migrations.CreateModel(
            name='KDSLog',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('station_id', models.CharField(max_length=100)),
                ('action_taken', models.CharField(choices=[('fire', 'Fire'), ('bump', 'Bump'), ('recall', 'Recall')], max_length=20)),
                ('delay_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kot_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kds_logs', to='restaurant_menu.kotlineitem')),
            ],
            options={
                'verbose_name': 'KDS Log',
                'verbose_name_plural': 'KDS Logs',
                'db_table': 'trn_kds_logs',
            },
        ),
        migrations.CreateModel(
            name='ItemKitchenMap',
            fields=[
                ('map_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_mappings', to='restaurant_menu.menuitem')),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_mappings', to='restaurant_menu.kitchen')),
            ],
            options={
                'verbose_name': 'Item Kitchen Map',
                'verbose_name_plural': 'Item Kitchen Map',
                'db_table': 'mst_item_kitchen_map',
                'unique_together': {('item', 'kitchen')},
            },
        ),
        migrations.AddIndex(
            model_name='kotheader',
            index=models.Index(fields=['order'], name='trn_kot_hea_order_i_755204_idx'),
        ),
        migrations.AddIndex(
            model_name='kotheader',
            index=models.Index(fields=['kitchen'], name='trn_kot_hea_kitchen_2a77b1_idx'),
        ),
        migrations.AddIndex(
            model_name='kotheader',
            index=models.Index(fields=['timestamp_created'], name='trn_kot_hea_timesta_46c2d8_idx'),
        ),
        migrations.AddIndex(
            model_name='kotamendment',
            index=models.Index(fields=['kot', 'created_at'], name='trn_kot_ame_kot_id_52390a_idx'),
        ),
        migrations.AddIndex(
            model_name='kotlineitem',
            index=models.Index(fields=['kot'], name='trn_kot_lin_kot_id_0e7928_idx'),
        ),
        migrations.AddIndex(
            model_name='kotlineitem',
            index=models.Index(fields=['item_status'], name='trn_kot_lin_item_st_307aa2_idx'),
        ),
        migrations.AddIndex(
            model_name='kdslog',
            index=models.Index(fields=['kot_line', 'created_at'], name='trn_kds_log_kot_lin_082609_idx'),
        ),
    ]
