# Generated by Django 5.2.8 on 2026-02-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0009_alter_kitchen_options_remove_kitchen_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kitchen Type',
                'verbose_name_plural': 'Kitchen Types',
                'db_table': 'mst_kitchen_types',
            },
        ),
        migrations.RemoveField(
            model_name='kdslog',
            name='kot_line',
        ),
        migrations.RemoveField(
            model_name='kotheader',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='kotamendment',
            name='kot',
        ),
        migrations.RemoveField(
            model_name='kotamendment',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='kotamendment',
            name='original_item',
        ),
        migrations.RemoveField(
            model_name='kotheader',
            name='order',
        ),
        migrations.RemoveField(
            model_name='kotheader',
            name='waiter',
        ),
        migrations.RemoveField(
            model_name='kotlineitem',
            name='kot',
        ),
        migrations.RemoveField(
            model_name='kotlineitem',
            name='chef',
        ),
        migrations.RemoveField(
            model_name='kotlineitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='ItemKitchenMap',
        ),
        migrations.DeleteModel(
            name='KDSLog',
        ),
        migrations.DeleteModel(
            name='Kitchen',
        ),
        migrations.DeleteModel(
            name='KOTAmendment',
        ),
        migrations.DeleteModel(
            name='KOTHeader',
        ),
        migrations.DeleteModel(
            name='KOTLineItem',
        ),
    ]
