# Generated by Django 5.2.8 on 2026-02-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0010_kitchentype_remove_kdslog_kot_line_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outlet_code', models.CharField(max_length=20, unique=True)),
                ('outlet_name', models.CharField(max_length=150)),
                ('outlet_type', models.CharField(choices=[('RESTAURANT', 'Restaurant'), ('BAR', 'Bar'), ('LOUNGE', 'Lounge'), ('ROOM_SERVICE', 'Room Service'), ('BANQUET', 'Banquet'), ('CAFE', 'Café'), ('NIGHT_CLUB', 'Night Club')], default='RESTAURANT', max_length=20)),
                ('location_description', models.CharField(blank=True, max_length=255, null=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('business_day_start_time', models.TimeField(blank=True, help_text='Time when business date starts (e.g., 06:00 AM)', null=True)),
                ('service_charge_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_table_service', models.BooleanField(default=True)),
                ('is_buffet_enabled', models.BooleanField(default=False)),
                ('is_kds_enabled', models.BooleanField(default=True)),
                ('allow_order_transfer', models.BooleanField(default=True)),
                ('allow_backdated_orders', models.BooleanField(default=False)),
                ('allow_item_cancel_after_print', models.BooleanField(default=False)),
                ('require_manager_approval_for_void', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Outlet',
                'verbose_name_plural': 'Outlets',
                'db_table': 'mst_outlets',
                'ordering': ['outlet_name'],
            },
        ),
    ]
