# Generated by Django 5.2.8 on 2026-02-15 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0011_outlet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('printer_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('backup_printer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('kds_display_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_kds_enabled', models.BooleanField(default=False)),
                ('is_printer_enabled', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kitchens_created', to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kitchens', to='restaurant_menu.outlet')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kitchens', to='restaurant_menu.kitchentype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kitchens_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mst_kitchens',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
