# Generated by Django 5.2.8 on 2026-02-16 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_setup', '0004_printer'),
        ('restaurant_menu', '0012_kitchen'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the kitchen station', max_length=255)),
                ('kds_display_id', models.CharField(blank=True, help_text='KDS display ID for this station', max_length=250, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this station is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kitchen', models.ForeignKey(blank=True, help_text='Optional: Assign this station to a specific kitchen', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='restaurant_menu.kitchen')),
                ('printer', models.ForeignKey(blank=True, help_text='Optional: Assign this station to a specific printer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations', to='master_setup.printer')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
