# Generated by Django 5.2.8 on 2026-02-16 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0013_kitchenstation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemKitchenMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_time', models.IntegerField(help_text='Expected time in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kitchen', models.ForeignKey(help_text='Kitchen', on_delete=django.db.models.deletion.CASCADE, related_name='item_mappings', to='restaurant_menu.kitchen')),
                ('kitchen_station', models.ForeignKey(help_text='Kitchen station', on_delete=django.db.models.deletion.CASCADE, related_name='item_mappings', to='restaurant_menu.kitchenstation')),
                ('menu_item', models.ForeignKey(help_text='Menu item', on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_mappings', to='restaurant_menu.menuitem')),
            ],
            options={
                'verbose_name': 'Item Kitchen Map',
                'verbose_name_plural': 'Item Kitchen Maps',
                'unique_together': {('menu_item', 'kitchen', 'kitchen_station')},
            },
        ),
    ]
