# Generated by Django 6.0.2 on 2026-02-17 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0014_itemkitchenmap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KOTStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the KOT status', max_length=250, null=True)),
                ('code', models.CharField(blank=True, help_text='Code of the KOT status', max_length=250, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the KOT status', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the KOT status active?')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='Create at for the KOT status')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='Update at for the KOT status')),
                ('create_by', models.ForeignKey(blank=True, help_text='User who created the KOT status', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kot_statuses_create_by', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(blank=True, help_text='User who updated the KOT status', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kot_statuses_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KOTType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the KOT type', max_length=250, null=True)),
                ('code', models.CharField(blank=True, help_text='Code of the KOT type', max_length=250, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the KOT type', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the KOT type active?')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='Create at for the KOT type')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='Update at for the KOT type')),
                ('create_by', models.ForeignKey(blank=True, help_text='User who created the KOT type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kot_types_create_by', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(blank=True, help_text='User who updated the KOT type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kot_types_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
