# Generated by Django 5.2.8 on 2026-02-17 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_setup', '0005_prioritylevel'),
        ('reception', '0008_remove_checkout_booking_checkout_check_in'),
        ('restaurant_menu', '0015_kotstatus_kottype'),
        ('rooms', '0004_rename_alloated_at_roomallotment_alloted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KOTHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField(blank=True, help_text='Business date for the KOT', null=True)),
                ('kot_number', models.CharField(blank=True, help_text='KOT number', max_length=250, null=True)),
                ('cover_count', models.IntegerField(blank=True, help_text='Cover count for the KOT', null=True)),
                ('is_urgent', models.BooleanField(default=False, help_text='Is urgent for the KOT')),
                ('is_reprint', models.BooleanField(default=False, help_text='Is reprint for the KOT')),
                ('reprint_count', models.IntegerField(default=0, help_text='Reprint count for the KOT')),
                ('printed_at', models.DateTimeField(blank=True, help_text='Printed at for the KOT', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Completed at for the KOT', null=True)),
                ('total_item_count', models.IntegerField(blank=True, help_text='Total item count for the KOT', null=True)),
                ('total_quantity', models.IntegerField(blank=True, help_text='Total quantity for the KOT', null=True)),
                ('is_stock_posted', models.BooleanField(default=False, help_text='Is stock posted for the KOT')),
                ('stock_posted_at', models.DateTimeField(blank=True, help_text='Stock posted at for the KOT', null=True)),
                ('transfer_at', models.DateTimeField(blank=True, help_text='Transfer at for the KOT', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='Cancelled at for the KOT', null=True)),
                ('cancelation_reason', models.TextField(blank=True, help_text='Cancelation reason for the KOT', null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='Create at for the KOT')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='Update at for the KOT')),
                ('cancelled_by', models.ForeignKey(blank=True, help_text='User who cancelled the KOT', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kot_headers_cancelled_by', to=settings.AUTH_USER_MODEL)),
                ('captain', models.ForeignKey(blank=True, help_text='Captain for the KOT', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kot_headers_captain', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the KOT', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kot_headers_created_by', to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(blank=True, help_text='Guest for the KOT', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kot_headers', to='reception.guest')),
                ('kitchen', models.ForeignKey(blank=True, help_text='Kitchen for the KOT', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kot_headers', to='restaurant_menu.kitchen')),
                ('kot_status', models.ForeignKey(blank=True, help_text='KOT status for the KOT', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kot_headers', to='restaurant_menu.kotstatus')),
                ('kot_type', models.ForeignKey(blank=True, help_text='KOT type for the KOT', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kot_headers', to='restaurant_menu.kottype')),
                ('order', models.ForeignKey(blank=True, help_text='Order for the KOT', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kot_headers', to='restaurant_menu.order')),
                ('outlet', models.ForeignKey(blank=True, help_text='Outlet for the KOT', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kot_headers', to='restaurant_menu.outlet')),
                ('printed_by', models.ForeignKey(blank=True, help_text='User who printed the KOT', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kot_headers_printed_by', to=settings.AUTH_USER_MODEL)),
                ('priority_level', models.ForeignKey(blank=True, help_text='Priority level for the KOT', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kot_headers', to='master_setup.prioritylevel')),
                ('room', models.ForeignKey(blank=True, help_text='Room for the KOT', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kot_headers', to='rooms.room')),
                ('shift_type', models.ForeignKey(blank=True, help_text='Shift type for the KOT', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kot_headers', to='master_setup.shifttype')),
                ('table', models.ForeignKey(blank=True, help_text='Table for the KOT', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kot_headers', to='restaurant_menu.tablesetup')),
                ('transfer_by', models.ForeignKey(blank=True, help_text='User who transferred the KOT', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kot_headers_transferred_by', to=settings.AUTH_USER_MODEL)),
                ('transfer_from_kitchen', models.ForeignKey(blank=True, help_text='Transfer from kitchen for the KOT', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kot_headers_transferred_from', to='restaurant_menu.kitchen')),
                ('transfer_to_kitchen', models.ForeignKey(blank=True, help_text='Transfer to kitchen for the KOT', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kot_headers_transferred_to', to='restaurant_menu.kitchen')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who updated the KOT', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kot_headers_updated_by', to=settings.AUTH_USER_MODEL)),
                ('waiter', models.ForeignKey(blank=True, help_text='Waiter for the KOT', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kot_headers_waiter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
