# Generated by Django 5.2.8 on 2026-02-18 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0016_kotheader'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KOTLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, help_text='Item code for the KOT line item', max_length=50, null=True)),
                ('item_name_snapshot', models.CharField(blank=True, help_text='Item name snapshot for the KOT line item', max_length=255, null=True)),
                ('course_number', models.PositiveIntegerField(default=1, help_text='Course number for the KOT line item')),
                ('fire_sequence', models.PositiveIntegerField(default=1, help_text='Fire sequence for the KOT line item')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity for the KOT line item', max_digits=10)),
                ('uom', models.CharField(help_text='Unit of measure for the KOT line item', max_length=50)),
                ('modifiers_text', models.TextField(blank=True, help_text='Modifiers text for the KOT line item', null=True)),
                ('cooking_instruction', models.TextField(blank=True, help_text='Cooking instruction for the KOT line item', null=True)),
                ('allergy_notes', models.TextField(blank=True, help_text='Allergy notes for the KOT line item', null=True)),
                ('is_complimentary', models.BooleanField(default=False)),
                ('item_status', models.CharField(choices=[('PENDING', 'Pending'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('BOUNCED', 'Bounced'), ('SERVED', 'Served'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('priority_level', models.CharField(choices=[('NORMAL', 'Normal'), ('VIP', 'VIP'), ('VVIP', 'VVIP'), ('STAFF', 'Staff'), ('COMPLIMENTARY', 'Complimentary')], default='NORMAL', max_length=20)),
                ('expected_prep_time_minutes', models.PositiveIntegerField(default=0, help_text='Expected prep time minutes for the KOT line item')),
                ('timestamp_fired', models.DateTimeField(blank=True, help_text='Timestamp fired for the KOT line item', null=True)),
                ('timestamp_start_cooking', models.DateTimeField(blank=True, help_text='Timestamp start cooking for the KOT line item', null=True)),
                ('timestamp_ready', models.DateTimeField(blank=True, help_text='Timestamp ready for the KOT line item', null=True)),
                ('timestamp_served', models.DateTimeField(blank=True, help_text='Timestamp served for the KOT line item', null=True)),
                ('timestamp_cancelled', models.DateTimeField(blank=True, null=True)),
                ('is_bounced', models.BooleanField(default=False)),
                ('bounce_reason', models.TextField(blank=True, null=True)),
                ('cancellation_reason_code', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancel_approved_by_manager', models.ForeignKey(blank=True, db_column='Cancel_Approved_By_Manager_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cancel_kot_items', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_kot_items', to=settings.AUTH_USER_MODEL)),
                ('chef', models.ForeignKey(blank=True, db_column='Chef_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_kot_items', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, help_text='Item for the KOT line item', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kot_line_items', to='restaurant_menu.menuitem')),
                ('kot', models.ForeignKey(help_text='KOT for the KOT line item', on_delete=django.db.models.deletion.CASCADE, related_name='kot_line_items', to='restaurant_menu.kotheader')),
                ('station', models.ForeignKey(blank=True, db_column='Station_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant_menu.kitchenstation')),
            ],
            options={
                'verbose_name': 'KOT Line Item',
                'verbose_name_plural': 'KOT Line Items',
                'db_table': 'trn_kot_line_items',
                'ordering': ['-created_at'],
            },
        ),
    ]
