# Generated by Django 6.0.2 on 2026-02-18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant_menu", "0017_kotlineitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KDSLog",
            fields=[
                ("log_id", models.BigAutoField(db_column="Log_ID", primary_key=True, serialize=False)),
                ("business_date", models.DateField(db_column="Business_Date")),
                (
                    "action_taken",
                    models.CharField(
                        choices=[
                            ("FIRE", "Fire"),
                            ("START", "Start"),
                            ("BUMP", "Bump"),
                            ("RECALL", "Recall"),
                            ("DELAY", "Delay"),
                            ("CANCEL", "Cancel"),
                        ],
                        db_column="Action_Taken",
                        max_length=20,
                    ),
                ),
                ("action_timestamp", models.DateTimeField(db_column="Action_Timestamp", default=django.utils.timezone.now)),
                ("delay_reason", models.TextField(blank=True, db_column="Delay_Reason", null=True)),
                ("device_id", models.CharField(blank=True, db_column="Device_ID", max_length=100, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, db_column="IP_Address", null=True)),
                (
                    "action_by",
                    models.ForeignKey(
                        db_column="Action_By",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kds_logs_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kitchen",
                    models.ForeignKey(
                        db_column="Kitchen_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kds_logs",
                        to="restaurant_menu.kitchen",
                    ),
                ),
                (
                    "kot_line",
                    models.ForeignKey(
                        db_column="KOT_Line_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kds_logs",
                        to="restaurant_menu.kotlineitem",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        db_column="Station_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kds_logs",
                        to="restaurant_menu.kitchenstation",
                    ),
                ),
            ],
            options={
                "verbose_name": "KDS Log",
                "verbose_name_plural": "KDS Logs",
                "db_table": "trn_kds_logs",
                "ordering": ["-action_timestamp", "-log_id"],
            },
        ),
    ]
