# Generated by Django 5.2.8 on 2026-02-18 16:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0018_kdslog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kdslog',
            options={'ordering': ['-action_timestamp', '-created_at'], 'verbose_name': 'KDS Log', 'verbose_name_plural': 'KDS Logs'},
        ),
        migrations.RemoveField(
            model_name='kdslog',
            name='log_id',
        ),
        migrations.AddField(
            model_name='kdslog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kdslog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='kdslog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='kdslog',
            name='action_by',
            field=models.ForeignKey(blank=True, help_text='User who took the action', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kds_logs_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kdslog',
            name='action_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='kdslog',
            name='delay_reason',
            field=models.TextField(blank=True, help_text='Reason for delay', null=True),
        ),
        migrations.AlterField(
            model_name='kdslog',
            name='device_id',
            field=models.CharField(blank=True, help_text='Device ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kdslog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address', null=True),
        ),
        migrations.AlterField(
            model_name='kdslog',
            name='kitchen',
            field=models.ForeignKey(blank=True, help_text='Kitchen for the KDS log', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kds_logs', to='restaurant_menu.kitchen'),
        ),
        migrations.AlterField(
            model_name='kdslog',
            name='kot_line',
            field=models.ForeignKey(blank=True, help_text='KOT line for the KDS log', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kds_logs', to='restaurant_menu.kotlineitem'),
        ),
        migrations.AlterField(
            model_name='kdslog',
            name='station',
            field=models.ForeignKey(blank=True, help_text='Kitchen station for the KDS log', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kds_logs', to='restaurant_menu.kitchenstation'),
        ),
        migrations.AlterModelTable(
            name='kdslog',
            table=None,
        ),
    ]
