# Generated by Django 6.0.2 on 2026-02-18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant_menu", "0019_alter_kdslog_options_remove_kdslog_log_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KOTAmendment",
            fields=[
                ("amendment_id", models.BigAutoField(db_column="Amendment_ID", primary_key=True, serialize=False)),
                ("business_date", models.DateField(db_column="Business_Date")),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("ADDED", "Added"),
                            ("CANCELLED", "Cancelled"),
                            ("QUANTITY_CHANGED", "Quantity Changed"),
                            ("ITEM_CHANGED", "Item Changed"),
                        ],
                        db_column="Action_Type",
                        max_length=30,
                    ),
                ),
                ("old_quantity", models.DecimalField(db_column="Old_Quantity", decimal_places=2, default=0, max_digits=10)),
                ("new_quantity", models.DecimalField(db_column="New_Quantity", decimal_places=2, default=0, max_digits=10)),
                ("reason_code", models.CharField(db_column="Reason_Code", max_length=100)),
                ("remarks", models.TextField(blank=True, db_column="Remarks", null=True)),
                ("timestamp_amended", models.DateTimeField(db_column="Timestamp_Amended", default=django.utils.timezone.now)),
                (
                    "amended_by",
                    models.ForeignKey(
                        db_column="Amended_By",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="amended_kot_amendments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kot",
                    models.ForeignKey(
                        db_column="KOT_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amendments",
                        to="restaurant_menu.kotheader",
                    ),
                ),
                (
                    "kot_line_item",
                    models.ForeignKey(
                        blank=True,
                        db_column="KOT_Line_ID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="amendments",
                        to="restaurant_menu.kotlineitem",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        db_column="Manager_ID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="managed_kot_amendments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "new_item",
                    models.ForeignKey(
                        blank=True,
                        db_column="New_Item_ID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="new_kot_amendments",
                        to="restaurant_menu.menuitem",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        db_column="Order_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amendments",
                        to="restaurant_menu.order",
                    ),
                ),
                (
                    "original_item",
                    models.ForeignKey(
                        db_column="Original_Item_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="original_kot_amendments",
                        to="restaurant_menu.menuitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "KOT Amendment",
                "verbose_name_plural": "KOT Amendments",
                "db_table": "trn_kot_amendments",
                "ordering": ["-timestamp_amended", "-amendment_id"],
            },
        ),
    ]
