# Generated by Django 6.0.2 on 2026-02-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant_menu", "0020_kotamendment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KOTCourseControl",
            fields=[
                ("course_control_id", models.BigAutoField(db_column="Course_Control_ID", primary_key=True, serialize=False)),
                ("course_number", models.PositiveIntegerField(db_column="Course_Number")),
                (
                    "fire_status",
                    models.CharField(
                        choices=[("HOLD", "Hold"), ("FIRED", "Fired"), ("COMPLETED", "Completed")],
                        db_column="Fire_Status",
                        default="HOLD",
                        max_length=20,
                    ),
                ),
                ("hold_until_time", models.TimeField(blank=True, db_column="Hold_Until_Time", null=True)),
                ("fired_timestamp", models.DateTimeField(blank=True, db_column="Fired_Timestamp", null=True)),
                (
                    "fired_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="Fired_By",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fired_kot_courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kot",
                    models.ForeignKey(
                        db_column="KOT_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_controls",
                        to="restaurant_menu.kotheader",
                    ),
                ),
            ],
            options={
                "verbose_name": "KOT Course Control",
                "verbose_name_plural": "KOT Course Controls",
                "db_table": "trn_kot_course_control",
                "ordering": ["-course_control_id"],
            },
        ),
    ]
