# Generated by Django 6.0.2 on 2026-02-18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant_menu", "0021_kotcoursecontrol"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KOTReprintLog",
            fields=[
                ("reprint_log_id", models.BigAutoField(db_column="Reprint_Log_ID", primary_key=True, serialize=False)),
                ("reprint_timestamp", models.DateTimeField(db_column="Reprint_Timestamp", default=django.utils.timezone.now)),
                ("reason", models.TextField(db_column="Reason")),
                (
                    "kot",
                    models.ForeignKey(
                        db_column="KOT_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reprint_logs",
                        to="restaurant_menu.kotheader",
                    ),
                ),
                (
                    "reprinted_by",
                    models.ForeignKey(
                        db_column="Reprinted_By",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reprinted_kots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "KOT Reprint Log",
                "verbose_name_plural": "KOT Reprint Logs",
                "db_table": "trn_kot_reprint_logs",
                "ordering": ["-reprint_timestamp", "-reprint_log_id"],
            },
        ),
    ]
