# Generated by Django 5.2.8 on 2026-02-19 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0022_kotreprintlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_code', models.CharField(max_length=30, unique=True)),
                ('property_name', models.CharField(max_length=150, unique=True)),
                ('property_type', models.CharField(choices=[('CAFE', 'Cafe'), ('CANTEEN', 'Canteen'), ('RESTAURANT', 'Restaurant'), ('HOTEL', 'Hotel'), ('RESORT', 'Resort'), ('MULTI_OUTLET_CHAIN', 'Multi-outlet Chain')], default='RESTAURANT', max_length=25)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=80)),
                ('country', models.CharField(max_length=80)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('gst_number', models.CharField(blank=True, max_length=30, null=True)),
                ('currency', models.CharField(max_length=10)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('website', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_properties', to='restaurant_menu.property')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'db_table': 'mst_properties',
                'ordering': ['property_name'],
            },
        ),
    ]
