# Generated by Django 5.2.8 on 2026-02-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0023_property'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.TextField(blank=True, help_text='Property address', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(blank=True, help_text='City name', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.CharField(blank=True, help_text='Country name', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='currency',
            field=models.CharField(blank=True, help_text='Currency', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Postal code', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_code',
            field=models.CharField(blank=True, help_text='Property code', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_name',
            field=models.CharField(blank=True, help_text='Property name', max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('CAFE', 'Cafe'), ('CANTEEN', 'Canteen'), ('RESTAURANT', 'Restaurant'), ('HOTEL', 'Hotel'), ('RESORT', 'Resort'), ('MULTI_OUTLET_CHAIN', 'Multi-outlet Chain')], default='RESTAURANT', help_text='Property type', max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.CharField(blank=True, help_text='State name', max_length=250, null=True),
        ),
        migrations.AlterModelTable(
            name='property',
            table=None,
        ),
    ]
