# Generated by Django 5.2.8 on 2026-02-22 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant_menu", "0024_remove_property_gst_number_remove_property_timezone_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertySettings",
            fields=[
                ("setting_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("enable_kot_module", models.BooleanField(default=False)),
                ("enable_table_management", models.BooleanField(default=False)),
                ("enable_room_module", models.BooleanField(default=False)),
                ("enable_folio_module", models.BooleanField(default=False)),
                ("enable_laundry_module", models.BooleanField(default=False)),
                ("enable_spa_module", models.BooleanField(default=False)),
                ("enable_inventory_module", models.BooleanField(default=False)),
                ("enable_credit_sales", models.BooleanField(default=False)),
                ("enable_multi_outlet", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="restaurant_menu.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Setting",
                "verbose_name_plural": "Property Settings",
                "db_table": "_property_settings",
                "ordering": ["-created_at"],
            },
        ),
    ]
