# Generated by Django 5.2.8 on 2026-02-22 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reception", "0009_stay"),
        ("restaurant_menu", "0025_propertysettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Folio",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("total_debit", models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ("total_credit", models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ("balance_amount", models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                (
                    "folio_status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("CLOSED", "Closed"), ("SETTLED", "Settled")],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="folios",
                        to="reception.stay",
                    ),
                ),
            ],
            options={
                "verbose_name": "Folio",
                "verbose_name_plural": "Folios",
                "ordering": ["-created_at"],
            },
        ),
    ]
