# Generated by Django 5.2.8 on 2026-02-22 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0026_folio'),
        ('restaurant_menu', '0026_remove_property_gst_number_remove_property_timezone_and_more'),
    ]

    operations = [
    ]
