# Generated by Django 5.2.8 on 2026-02-22 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant_menu", "0027_merge_20260222_1701"),
    ]

    operations = [
        migrations.CreateModel(
            name="FolioTransaction",
            fields=[
                ("folio_trn_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("source_module_id", models.CharField(max_length=100)),
                ("reference_id", models.BigIntegerField()),
                ("debit_amount", models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ("credit_amount", models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ("transaction_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "folio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="restaurant_menu.folio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Folio Transaction",
                "verbose_name_plural": "Folio Transactions",
                "ordering": ["-transaction_date", "-created_at"],
            },
        ),
    ]
