# Generated by Django 5.2.8 on 2026-02-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0028_foliotransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=150, unique=True)),
                ('module_code', models.CharField(max_length=50, unique=True)),
                ('is_postable_to_folio', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Source Module',
                'verbose_name_plural': 'Source Modules',
                'ordering': ['module_name'],
            },
        ),
    ]
