# Generated by Django 5.2.8 on 2026-02-24 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_setup', '0006_billtype'),
        ('reception', '0011_alter_stay_id'),
        ('restaurant_menu', '0029_sourcemodule'),
        ('rooms', '0004_rename_alloated_at_roomallotment_alloted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(blank=True, help_text='Bill number', max_length=250, null=True, unique=True)),
                ('sub_total', models.DecimalField(blank=True, decimal_places=2, help_text='Sub total for the bill', max_digits=10, null=True)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, help_text='Discount value for the bill', max_digits=10, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Discount amount for the bill', max_digits=10, null=True)),
                ('extra_charge_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Extra charge amount for the bill', max_digits=10, null=True)),
                ('service_charge_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Service charge amount for the bill', max_digits=10, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Tax amount for the bill', max_digits=10, null=True)),
                ('round_off', models.DecimalField(blank=True, decimal_places=2, help_text='Round off for the bill', max_digits=10, null=True)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, help_text='Grand total for the bill', max_digits=10, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('partially_refunded', 'Partially Refunded'), ('fully_refunded', 'Fully Refunded')], default='pending', help_text='Payment status for the bill', max_length=50)),
                ('bill_status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('void', 'Void'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded'), ('fully_refunded', 'Fully Refunded')], default='draft', help_text='Bill status for the bill', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the bill was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the bill was last updated')),
                ('bill_type', models.ForeignKey(blank=True, help_text='Bill type for the bill', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_masters', to='master_setup.billtype')),
                ('created_by', models.ForeignKey(blank=True, help_text='Created by for the bill', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_masters', to=settings.AUTH_USER_MODEL)),
                ('discount_type', models.ForeignKey(blank=True, help_text='Discount type for the bill', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_masters', to='master_setup.discounttype')),
                ('folio', models.ForeignKey(blank=True, help_text='Folio for the bill', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_masters', to='restaurant_menu.folio')),
                ('guest', models.ForeignKey(blank=True, help_text='Guest for the bill', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_masters', to='reception.guest')),
                ('order', models.ForeignKey(blank=True, help_text='Order for the bill', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_masters', to='restaurant_menu.order')),
                ('outlet', models.ForeignKey(blank=True, help_text='Outlet for the bill', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_masters', to='restaurant_menu.outlet')),
                ('property', models.ForeignKey(blank=True, help_text='Property for the bill', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_masters', to='restaurant_menu.property')),
                ('room', models.ForeignKey(blank=True, help_text='Room for the bill', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_masters', to='rooms.room')),
                ('source_module', models.ForeignKey(blank=True, help_text='Source module for the bill', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_masters', to='restaurant_menu.sourcemodule')),
                ('stay', models.ForeignKey(blank=True, help_text='Stay for the bill', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_masters', to='reception.stay')),
                ('tax_type', models.ForeignKey(blank=True, help_text='Tax type for the bill', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_masters', to='master_setup.taxtype')),
            ],
            options={
                'verbose_name': 'Bill Master',
                'verbose_name_plural': 'Bill Masters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name_snapshot', models.TextField(blank=True, help_text='Item name snapshot for the bill line item', null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Quantity for the bill line item', max_digits=10, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, help_text='Rate for the bill line item', max_digits=10, null=True)),
                ('gross_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount for the bill line item', max_digits=10, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Discount amount for the bill line item', max_digits=10, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Net amount for the bill line item', max_digits=10, null=True)),
                ('is_complementary', models.BooleanField(default=False, help_text='Is the bill line item a complementary item?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the bill line item was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the bill line item was last updated')),
                ('item', models.ForeignKey(blank=True, help_text='Item for the bill line item', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_line_items', to='restaurant_menu.menuitem')),
                ('bill_master', models.ForeignKey(blank=True, help_text='Bill master for the bill line item', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_line_items', to='restaurant_menu.billmaster')),
            ],
        ),
    ]
