# Generated by Django 5.2.8 on 2026-01-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the guest (max 256 characters)', max_length=256, null=True)),
                ('gender', models.CharField(blank=True, help_text='Gender of the guest (max 256 characters)', max_length=256, null=True)),
                ('dob', models.DateField(blank=True, help_text='Date of birth of the guest (max 256 characters)', null=True)),
                ('nationalitly', models.CharField(blank=True, help_text='Nationality of the guest (max 256 characters)', max_length=256, null=True)),
                ('id_proof_type', models.CharField(blank=True, help_text='ID proof type of the guest (max 256 characters)', max_length=256, null=True)),
                ('id_proof_number', models.CharField(blank=True, help_text='ID proof number of the guest (max 256 characters)', max_length=256, null=True)),
                ('phone', models.CharField(blank=True, help_text='Mobile number of the guest (max 256 characters)', max_length=256, null=True)),
                ('email', models.CharField(blank=True, help_text='Email of the guest (max 256 characters)', max_length=256, null=True)),
                ('address', models.CharField(blank=True, help_text='Address of the guest (max 256 characters)', max_length=256, null=True)),
                ('guest_type', models.CharField(blank=True, help_text='Guest type of the guest (max 256 characters)', max_length=256, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Remarks of the guest (max 256 characters)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the guest active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the guest was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the guest was last updated')),
            ],
        ),
    ]
