# Generated by Django 5.2.8 on 2026-01-17 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_setup', '0003_country_created_at_country_updated_at_and_more'),
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='age',
            field=models.IntegerField(blank=True, help_text='Age of the guest (max 256 characters)', null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='city',
            field=models.CharField(blank=True, help_text='City of the guest (max 256 characters)', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='master_setup.country'),
        ),
        migrations.AddField(
            model_name='guest',
            name='state',
            field=models.CharField(blank=True, help_text='State of the guest (max 256 characters)', max_length=256, null=True),
        ),
    ]
