# Generated by Django 5.2.8 on 2026-01-18 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0002_guest_age_guest_city_guest_country_guest_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='nationalitly',
            new_name='nationality',
        ),
    ]
