# Generated by Django 5.2.8 on 2026-01-19 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_setup', '0003_country_created_at_country_updated_at_and_more'),
        ('reception', '0003_rename_nationalitly_guest_nationality'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('check_in_date', models.DateTimeField()),
                ('check_out_date', models.DateTimeField()),
                ('no_of_adults', models.IntegerField(blank=True, default=1, help_text='Number of adults', null=True)),
                ('no_of_children', models.IntegerField(blank=True, default=0, help_text='Number of children', null=True)),
                ('package_type', models.CharField(blank=True, choices=[('Single', 'Single'), ('Double', 'Double'), ('Family', 'Family')], help_text='Package type of the booking (max 256 characters)', max_length=256, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('special_request', models.TextField(blank=True, help_text='Special request of the guest (max 256 characters)', null=True)),
                ('booking_status', models.CharField(blank=True, help_text='Booking status (max 256 characters)', max_length=256, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Remarks of the booking (max 256 characters)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the booking was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the booking was last updated')),
                ('booking_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='master_setup.bookingsource')),
                ('discount_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='master_setup.discounttype')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='reception.guest')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rooms.room')),
            ],
        ),
    ]
