# Generated by Django 5.2.8 on 2026-01-23 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_setup', '0003_country_created_at_country_updated_at_and_more'),
        ('reception', '0004_booking'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='no_of_adults',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='no_of_children',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='package_type',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Double', 'Double'), ('Family', 'Family')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='special_request',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='reception.booking')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='reception.guest')),
                ('payment_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='master_setup.paymentmode')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
