# Generated by Django 5.2.8 on 2026-01-24 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_setup', '0003_country_created_at_country_updated_at_and_more'),
        ('reception', '0006_alter_booking_discount_amount_and_more'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_out_time', models.DateTimeField(auto_now_add=True, help_text='Date and time when the guest checked out')),
                ('late_check_out_charge', models.DecimalField(decimal_places=2, default=0.0, help_text='Late check-out charge', max_digits=10)),
                ('minibar_charge', models.DecimalField(decimal_places=2, default=0.0, help_text='Minibar charge', max_digits=10)),
                ('damage_charge', models.DecimalField(decimal_places=2, default=0.0, help_text='Damage charge', max_digits=10)),
                ('other_charge', models.DecimalField(decimal_places=2, default=0.0, help_text='Other charge', max_digits=10)),
                ('final_bill_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Final bill amount', max_digits=10)),
                ('remarks', models.TextField(blank=True, help_text='Remarks of the check-out (max 256 characters)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the check-out was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the check-out was last updated')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_outs', to='reception.booking')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_outs', to='reception.guest')),
                ('payment_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_outs', to='master_setup.paymentmode')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_outs', to='rooms.room')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_outs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Check Out',
                'verbose_name_plural': 'Check Outs',
                'ordering': ['-check_out_time'],
            },
        ),
    ]
