# Generated by Django 5.2.8 on 2026-01-24 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0007_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='booking',
        ),
        migrations.AddField(
            model_name='checkout',
            name='check_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_outs', to='reception.checkin'),
        ),
    ]
