# Generated by Django 6.0.2 on 2026-02-22 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reception", "0008_remove_checkout_booking_checkout_check_in"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stay",
            fields=[
                ("stay_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("check_in_date", models.DateTimeField()),
                ("expected_check_out_date", models.DateTimeField(blank=True, null=True)),
                ("actual_check_out_date", models.DateTimeField(blank=True, null=True)),
                (
                    "stay_status",
                    models.CharField(
                        choices=[
                            ("CHECKED_IN", "Checked In"),
                            ("CHECKED_OUT", "Checked Out"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="CHECKED_IN",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stays",
                        to="reception.booking",
                    ),
                ),
                (
                    "check_in",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stays",
                        to="reception.checkin",
                    ),
                ),
                (
                    "check_out",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stays",
                        to="reception.checkout",
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stays",
                        to="reception.guest",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stays",
                        to="rooms.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stay",
                "verbose_name_plural": "Stays",
                "ordering": ["-created_at"],
            },
        ),
    ]
