# Generated by Django 5.2.8 on 2026-02-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0009_stay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stay',
            name='stay_id',
        ),
        migrations.AddField(
            model_name='stay',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
