# Generated by Django 5.2.8 on 2026-02-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0010_remove_stay_stay_id_stay_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stay',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
