# Generated by Django 5.2.8 on 2026-01-27 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the menu category (max 256 characters)', max_length=256, null=True, unique=True)),
                ('code', models.CharField(blank=True, help_text='Code of the menu category (max 256 characters)', max_length=256, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the menu category (max 256 characters)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the menu category active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the menu category was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the menu category was last updated')),
            ],
        ),
        migrations.CreateModel(
            name='MenuSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the menu sub category (max 256 characters)', max_length=256, null=True, unique=True)),
                ('code', models.CharField(blank=True, help_text='Code of the menu sub category (max 256 characters)', max_length=256, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the menu sub category (max 256 characters)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the menu sub category active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the menu sub category was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the menu sub category was last updated')),
                ('menu_category', models.ForeignKey(help_text='Menu category to which the menu sub category belongs', on_delete=django.db.models.deletion.CASCADE, related_name='menu_sub_categories', to='restaurant.menucategory')),
            ],
        ),
    ]
