# Generated by Django 5.2.8 on 2026-01-27 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_setup', '0004_printer'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the menu item (max 256 characters)', max_length=256, null=True, unique=True)),
                ('code', models.CharField(blank=True, help_text='Code of the menu item (max 256 characters)', max_length=256, null=True, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price of the menu item (max 10 digits, 2 decimal places)', max_digits=10, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the menu item (max 256 characters)', null=True)),
                ('food_type', models.CharField(blank=True, help_text='Food type to which the menu item belongs', max_length=256, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the menu item active?')),
                ('recipe_linked', models.BooleanField(default=False, help_text='Is the menu item linked to a recipe?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the menu item was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the menu item was last updated')),
                ('menu_category', models.ForeignKey(help_text='Menu category to which the menu item belongs', on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurant.menucategory')),
                ('menu_sub_category', models.ForeignKey(help_text='Menu sub category to which the menu item belongs', on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurant.menusubcategory')),
                ('printer_id', models.ForeignKey(blank=True, help_text='Printer to which the menu item belongs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='master_setup.printer')),
                ('tax_type', models.ForeignKey(blank=True, help_text='Tax type to which the menu item belongs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='master_setup.taxtype')),
            ],
        ),
    ]
